### ISSUE TITLE
Large heuristic function cost

### ISSUE THREAD

**Issue by glenwatson** [ssaric/algoviz#1]
I think your heuristic function cost is dwarfing the already traveled cost.
![Astar](https://user-images.githubusercontent.com/943343/72212286-1a550000-348e-11ea-8e84-88b1b38b9c3b.png)

Maybe don't multiple by 100 [here](https://github.com/ssaric/algoviz/blob/012c60acb2fa452ee5a3c477fe799577cc1f0ea4/src/util/GridNode.js#L1)?

**Comment by ssaric** [comment]
> I think your heuristic function cost is dwarfing the already traveled cost.
> ![Astar](https://user-images.githubusercontent.com/943343/72212286-1a550000-348e-11ea-8e84-88b1b38b9c3b.png)
> 
> Maybe don't multiple by 100 [here](https://github.com/ssaric/algoviz/blob/190f283/src/algorithms/AStar.js#L81)?

You are absolutely right. This was a leftover from my experiments. I plan to add choosing the algorithm heuristic manually. I will probably have it done by tomorrow.

**Comment by ssaric** [comment]
Added different heuristics.
